version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: career_nest_app
        volumes:
            - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - laravel

    mysql:
        image: mysql:5.7
        container_name: career_nest_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: career_nest
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - laravel

volumes:
    mysql_data:

networks:
    laravel:
        driver: bridge
